
server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:3308/microservice
    username: postgres
    password: Aroonay@09

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  config:
    import: configserver:http://localhost:8085


