server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: root
    password: Aroonay@09
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  config:
    import: configserver:http://localhost:8085


